<?= $context->form_tag_for(array('admin', $context->post, 'key'), null, &$f) ?>
	<?= $f->errors() ?>
	<p>
		<?= $f->label('title') ?>
		<?= $f->text_field('title') ?>
	</p>
	<p>
		<?= $f->label('body')?>
		<?= $f->text_area('body') ?>
	</p>
	<p>
		<?= $f->submit() ?> | <?= $f->reset() ?> | <?= $context->link_to('Cancel', 'admin/posts') ?>
	</p>
<?= $context->end_form_tag() ?>

<? if($context->post->exists()) echo $context->button_to('Delete', array('delete_admin/post', array('id' => $context->post->key)), array('method' => 'delete', 'confirm' => 'Are you sure?')); ?>