<?= $context->errors_for('post') ?>

<?= $context->form_tag_for(array('admin', $context->post, 'key')) ?>
	<p>
		<label for="post_title">Title</label>
		<?= $context->text_field('post', 'title') ?>
	</p>
	<p>
		<label for="post_body">Body</label>
		<?= $context->text_area('post', 'body') ?>
	</p>
	<p>
		<?= $context->submit_button() ?> or <?= $context->link_to('Cancel', 'admin/posts') ?>
	</p>
<?= $context->end_form_tag() ?>

<?= $context->button_to('Delete', array('delete_admin/post', array('id' => $context->post->key)), array('method' => 'delete', 'confirm' => 'Are you sure?')) ?>