<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
	"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<title><?= $context->write_title() ?></title>
	<?= $context->stylesheet_tag() ?>
	<?= $context->rss_tag('KDE Games (RSS 2.0)', 'rss') ?>
	<?= $context->javascript_include_tag() ?>
</head>

<body>
<div id="header">
	<div id="breadcrumbs">
		<?= $context->lay_breadcrumbs() ?>
	</div>
	<ul>
		<?= $context->link_to_controllers('home:/', 'catalogue', 'news', 'about') ?>
		<li id="empty"></li>
	</ul>
</div>

<div id="top"><div id="bottom">
<div id="airlock">
	<? if(isset($context->sidebar)) echo self::render_partial("sidebars/{$context->sidebar}") ?>
	<? if($context->in_admin()) echo self::render_partial('admin/navigation'); ?>
	<?= $context->write_flash('success') ?>

<?= $context->yield() ?>
</div>
</div></div>

<div id="footer">
	<p>
		Maintained by <a href="mailto:emilsedgh@gmail.com">games.kde.org</a><br />
		KDE&reg; and <a href="#">the K Desktop Environment&reg; Logo</a> are registered trademarks of <a href="http://ev.kde.org/">the KDE e.V.</a>
		| <a href="http://www.kde.org/contact/impressum.php">Legal</a>
	</p>
</div>

</body>
</html>
