<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
	"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<title><?= $helpers->write_title() ?></title>
	<?= $helpers->stylesheet_tag() ?>
</head>

<body>
<div id="header">
	<div id="breadcrumbs">
		<!-- KDEGames Home &raquo; <span>Welcome!</span> -->
		<?= $helpers->lay_breadcrumbs() ?>
	</div>
	<ul>
		<!-- <li id="home" class="selected"><?= $helpers->link_to('Home', '/') ?></li>
		<li id="catalogue"><?= $helpers->link_to('Catalogue', '/catalogue') ?></li>
		<li id="news"><?= $helpers->link_to('News', '/news') ?></li>
		<li id="about"><?= $helpers->link_to('About', '/about') ?></li> -->
		<?= $helpers->link_to_controllers('home:/', 'catalogue', 'news', 'about') ?>
		<li id="empty"></li>
	</ul>
</div>

<div id="top"><div id="bottom">
<div id="airlock">
<?= $this->content ?>
<?php $this->render_file('test'); ?>
</div>
</div></div>

<div id="footer">
	<p>
		Maintained by <a href="mailto:emilsedgh@gmail.com">games.kde.org</a><br />
		KDE&reg; and <a href="#">the K Desktop Environment&reg; Logo</a> are registered trademarks of <a href="http://ev.kde.org/">the KDE e.V.</a>
		| <a href="http://www.kde.org/contact/impressum.php">Legal</a>
	</p>
</div>

</body>
</html>
