<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
	"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<title><?= $helpers->write_title() ?></title>
	<?= $helpers->stylesheet_tag() ?>
	<?= $helpers->rss_tag('KDE Games (RSS 2.0)', 'rss') ?>
	<?= $helpers->javascript_include_tag() ?>
</head>

<body>
<div id="header">
	<div id="breadcrumbs">
		<?= $helpers->lay_breadcrumbs() ?>
	</div>
	<ul>
		<?= $helpers->link_to_controllers('home:/', 'catalogue', 'news:/posts', 'about') ?>
		<li id="empty"></li>
	</ul>
</div>

<div id="top"><div id="bottom">
<div id="airlock">
<?= $this->content ?>
</div>
</div></div>

<div id="footer">
	<p>
		Maintained by <a href="mailto:emilsedgh@gmail.com">games.kde.org</a><br />
		KDE&reg; and <a href="#">the K Desktop Environment&reg; Logo</a> are registered trademarks of <a href="http://ev.kde.org/">the KDE e.V.</a>
		| <a href="http://www.kde.org/contact/impressum.php">Legal</a>
	</p>
</div>

</body>
</html>
