<?= self::render_partial('promo') ?>

<?= $context->start_em('whatsnew') ?>
<div class="kdegames">
<h2>What's new in KDE Games?</h2>
<ul>
<?php
for($i = 0; $i < $context->latest->count(); $i++) {
	$item = $context->latest[$i];
?>
<li>
	<?= $context->link_to_post($item) ?>
	<span>| <?= $context->time_distance_in_words($item->created_at) ?></span>
</li>
<?php
}
?>
</ul>
</div>
<div class="divider"></div>
<div class="kde">
<h2>What's new in KDE?</h2>
<ul>
<?php
for($i = 0; $i < 5; $i++) {
	$item = $context->kde_feed->channel->item[$i];
?>
<li>
	<a href="<?= $item->link ?>"><?= $item->title ?></a>
	<span>| <?= $context->time_distance_in_words($item->pubDate) ?></span>
</li>
<?php
}
?>
</ul>
</div>
<br class="clear" />
<?= $context->end_em() ?>