<?= $this->render_partial('promo') ?>

<?= $helpers->start_em('whatsnew') ?>
<div class="kdegames">
<h2>What's new in KDE Games?</h2>
<ul>
<?php
for($i = 0; $i < $this->latest->count(); $i++) {
	$item = $this->latest[$i];
?>
<li>
	<?= $helpers->link_to($item->title, array('controller' => 'news', 'action' => 'archive', 'key' => $item->key)) ?>
	<span><?= date('H:i d/m/y', strtotime($item->created_at)) ?></span>
</li>
<?php
}
?>
</ul>
</div>
<div class="divider"></div>
<div class="kde">
<h2>What's new in KDE?</h2>
<ul>
<?php
for($i = 0; $i < 5; $i++) {
	$item = $this->kde_feed->channel->item[$i];
?>
<li>
	<a href="<?= $item->link ?>"><?= $item->title ?></a>
	<span><?= date('H:i d/m/y', strtotime($item->pubDate)) ?></span>
</li>
<?php
}
?>
</ul>
</div>
<br class="clear" />
<?= $helpers->end_em() ?>